name: Build

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup VCPKG
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: aafb8b71554a4590aa5108bdb5005d81d72db6c1

    - name: Integrate vcpkg
      run: vcpkg integrate install

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Mod_${{env.BUILD_CONFIGURATION}}
        path: |
          x64\${{env.BUILD_CONFIGURATION}}\

    - name: Create Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: x64/${{env.BUILD_CONFIGURATION}}/*.dll
        draft: true
        makeLatest: true
